language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - os: osx
      osx_image: xcode11
      language: shell
      env: TOXENV=py37
    - os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install -U pip
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOXENV=py37
install:
  - pip install -U pip tox-travis
script:
  - tox
